//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sidebar.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sidebar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Sidebar is on the left side of the screen 的本地化字符串。
        /// </summary>
        internal static string SidebarDirection_Left {
            get {
                return ResourceManager.GetString("SidebarDirection_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sidebar is on the right side of the screen, default 的本地化字符串。
        /// </summary>
        internal static string SidebarDirection_Right {
            get {
                return ResourceManager.GetString("SidebarDirection_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flyout window closed event. Occurs after the window is closed, allowing the tile to perform cleanup tasks. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_FlyoutClosed {
            get {
                return ResourceManager.GetString("TileHostEvent_FlyoutClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flyout window closing event. When the flyout window is about to close, the tile can decide whether to close it. Passes the Flyout&apos;s sender and the flyout&apos;s client area element. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_FlyoutClosing {
            get {
                return ResourceManager.GetString("TileHostEvent_FlyoutClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flyout window initialization event. When the user opens the flyout, this event is triggered, passing the flyout&apos;s client area element. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_FlyoutInit {
            get {
                return ResourceManager.GetString("TileHostEvent_FlyoutInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flyout window size changed event. Passes the flyout window size and client area size. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_FlyoutResize {
            get {
                return ResourceManager.GetString("TileHostEvent_FlyoutResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flyout window load event. When the user opens the flyout, this event is raised after the flyout is loaded, passing the flyout&apos;s client area element. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_FlyoutShow {
            get {
                return ResourceManager.GetString("TileHostEvent_FlyoutShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show property window event. When the user selects &quot;Properties&quot; from the tile&apos;s context menu, this event requests the property window. The tile may need to implement this. Note: The property window must be destroyed before unload. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_Properties {
            get {
                return ResourceManager.GetString("TileHostEvent_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size changed event. Passes the tile&apos;s overall size and client area size. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_Resize {
            get {
                return ResourceManager.GetString("TileHostEvent_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sidebar direction changed event. Fires when the sidebar is moved to the left or right side. Generally tiles do not need to respond unless required. Note: This is a pure position change, not a text direction change. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_SidebarDirectionChanged {
            get {
                return ResourceManager.GetString("TileHostEvent_SidebarDirectionChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The theme change event will pass in the new theme name. Tiles can automatically switch themes based on the theme name. 的本地化字符串。
        /// </summary>
        internal static string TileHostEvent_ThemeChanged {
            get {
                return ResourceManager.GetString("TileHostEvent_ThemeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically handle tile height adjustment. When adjusting, the tile&apos;s AutoSize is enabled and cannot be changed. 的本地化字符串。
        /// </summary>
        internal static string TileOverflow_Auto {
            get {
                return ResourceManager.GetString("TileOverflow_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clip overflowing content (hidden). 的本地化字符串。
        /// </summary>
        internal static string TileOverflow_Hidden {
            get {
                return ResourceManager.GetString("TileOverflow_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When content overflows, request whether to allow exceeding the maximum height. (Not used) 的本地化字符串。
        /// </summary>
        internal static string TileOverflow_Resize {
            get {
                return ResourceManager.GetString("TileOverflow_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When content overflows, proportionally scale to a suitable height. 的本地化字符串。
        /// </summary>
        internal static string TileOverflow_Scale {
            get {
                return ResourceManager.GetString("TileOverflow_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show scrollbar for overflowing content. 的本地化字符串。
        /// </summary>
        internal static string TileOverflow_Scroll {
            get {
                return ResourceManager.GetString("TileOverflow_Scroll", resourceCulture);
            }
        }
    }
}
